### ISSUE TITLE
修复投影时向后的疾跑

### ISSUE THREAD

**Issue by Dg32z** [223225zzzkkk/easyplaceFix#4]
在打印时会允许玩家可以向后疾跑,作者能不能加个功能解决这个问题QAQ

**Comment by 223225zzzkkk** [comment]
没看懂，是希望有一个向后疾跑的功能吗？

**Comment by Dg32z** [comment]
> 没看懂，是希望有一个向后疾跑的功能吗？

有个问题就是，在打印机打印建筑时，玩家向后也是疾跑的，这很有可能在有反作弊的服务器上被检测，希望能解决这个问题

**Comment by 223225zzzkkk** [comment]
但是我这项目不是打印机啊老铁？
